import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-gray-200 to-red-400">
          <div className="h-24">
            <NavBar />
          </div>
          <div className="h-[calc(100vh-6rem)]">
          {children}
          </div>
        </div>
      </body>
    </html>
  );
}
